### ISSUE TITLE
The example has typo in creating classname

### ISSUE THREAD

**Issue by myworkpool** [marcushat/RollingCurlX#1]
@marcushat 

Hi'm Im very please with your class, it help me a lot and I would like to be one of contributor, if possible.

The first issue is about the typo in the object creation, in MD file

$RollingCurlX = new RollinCurlX(10);

should be  (add 'g' in rolling)

$RollingCurlX = new RollingCurlX(10);

Thanks

**Comment by marcushat** [comment]
Fixed the typo, nice catch. 
And I would love for you to help contribute. Any improvements will be greatly appreciated.
