### ISSUE TITLE
'

### ISSUE THREAD

**Issue by naviace** [marcushat/RollingCurlX#11]
I occasionally get $request_info['http_code'] as zero, that means the request was failed, can I get to see the actual error message thrown by curl? Also the $request_info['total_time']  and $time doesn't match up in the callback? what actual time do these variables represent?

**Comment by marcushat** [comment]
You should be able to see all available information about the request with $request_info as it's returned by curl_getinfo($ch). And $time represents the time since the request was added to the curl_multi handle and when it returns. How much is this off by? It shouldnt be much at all

**Comment by nviror** [comment]
Yes, I see $request_info is like a face of curl_getinfo($ch) but it doesn't include data from curl_error and curl_errorno.

I get occasional failed requests at time:
$request_info['total_time'] = 0.697764 and $time = 3100.6419658661
when my timeout is 5s

**Comment by marcushat** [comment]
Going to pass $ch itself as part of $request_info so you can do whatever you want with it.

**Comment by marcushat** [comment]
more info in $request_info coming in next update. errno and error code will be included

**Comment by marcushat** [comment]
Resolved in newest version. added `handle`, `curle`, and `curle_msg` to `$request_info`
