### ISSUE TITLE
How to know whether all requests are completed if we are in a call_back function of one of the request?

### ISSUE THREAD

**Issue by shubham19may** [marcushat/RollingCurlX#12]
I am adding some more requests from call_back function of already added request. But the problem is that, if the already added request (which is adding new requests in its call_back function) is the last request to get complete, the new requests it is adding, wont execute. So is there any way to know that if all requests present in $RCX object are completed or not in call_back function of any added requests? So that if all of them are complete i can again call $RCX->execute();

**Comment by marcushat** [comment]
Thanks for reporting the issue. This most definitely should not happen as the callback for the completed request is executed before checking if there's any more requests left in tge queue(there should be if one was added during the callback). 
I just got done using this class very recursively last week and I didn't have any issues with this.
Can you post the the problem code? If it's a bug I'll try to get to the bottom of this asap

**Comment by shubham19may** [comment]
Thank you for your reply. I didn't know that.

**Comment by tommiehansen** [comment]
If you're doing multiple urls have them as array and then use count($array) and then in your complete callback check if the number is that number and if it is execute a finished() function.

Something like below:

```
$RCX = new RollingCurlX($threads);
$RCX->setTimeout(5000);

$url_array = array(
    'google.com',
    'apple.com',
    'microsoft.com'
)

// all complete function
function allComplete(){
    echo 'all is complete';
}

// complete for each request
$complete = function($response, $url, $request_info, $data, $time) {

    $num = $data['num'];
    $total = $data['total'];

    // proess stuff etc
    // ...
    // ...
    // ...

    // run allComplete function
    if( $num = $total ) {
        allComplete();
    }

}

// loop through $url_array
$num = 0;
foreach($url_array as $url){

    $options = [CURLOPT_FOLLOWLOCATION => false];

    $data = array(
        'RCX' => $RCX,
        'complete' => $complete,
        'num' => $num,
        'total' => count($url_list),
    );

    $RCX->addRequest($url, null, $complete, $data, $options);

}

```

**Comment by marcushat** [comment]
Either do after execute() or pass the necessary info with $user_data(you can pass the number of requests and deincrement until it's zero)
