### ISSUE TITLE
Fatal error: Class 'ScriptTimer' not found in rollingcurlx.class.php on line 238

### ISSUE THREAD

**Issue by logless** [marcushat/RollingCurlX#15]
there is a call to undefined class...

**Comment by marcushat** [comment]
Oh sorry, my bad. That's a timer class I use internally, was supposed to be removed from the github version. Will fix

**Comment by logless** [comment]
Just removed the references and it works. I would like a "retry" feature for failed requests and also a "max_retries" variable. Can you modify it so that it is possible to run addRequest() after execute() so that failed (based on returned html) requests are re-added to end of queue for n number of retries?

**Comment by logless** [comment]
Just to mention that I managed to emulate a "retry" feature by simply encapsulating the code in a do-while loop. However, a built-in functionality will still be nice. Props for the good work anyway!

**Comment by marcushat** [comment]
You can do this pretty easily with $user_data. In your complete callback for the first addRequest just fire addRequest again and pass the retry number in $user_data.

**Comment by marcushat** [comment]
resolved
