### ISSUE TITLE
How to add retry in RollingCurlX?

### ISSUE THREAD

**Issue by nikola8** [marcushat/RollingCurlX#16]
I would like to implement this code that retires connection several times:

$curl = curl_init();
curl_setopt_array($curl, $options);
$response = curl_exec($curl);
$retry = 0;
while(curl_errno($curl) == 28 && $retry < 5){
    $response = curl_exec($curl);
    $retry++;
}

Is there any way to implement it inside your class?

**Comment by marcushat** [comment]
Just pass $retry and $rcx in $user_data and fire off a new request if necessary inside the callback function

**Comment by nikola8** [comment]
But if I call it from callback function and this is multi threading where requests are running in parallel then it can't work.

I understand that I should implement this somewhere after this line inside function execute():

while(($mh_status = curl_multi_exec($multi_handle, $active)) == CURLM_CALL_MULTI_PERFORM);

**Comment by marcushat** [comment]
It'll add the retry request to the request queue. It definitely works, I've used it quite a bit.

**Comment by marcushat** [comment]
And php is single threaded. Asynchronous not multi-threaded.

**Comment by nikola8** [comment]
Can you please post example of your code where you applied retires in curl.

**Comment by marcushat** [comment]
Yeah, sure

``` php
$complete = function($response,..., $user_data){
     foreach($user_data as $var_name => $val) {
          ${$var_name} =& $val;
     }
     if(!$response && $retry < 5) {
          $retry++;          
          $rcx->addRequest($url, null, $complete, $user_data);
     }
};
$user_data = [
     'rcx' => $rcx,
     'url' => $url, 
     'complete' =>$complete,
     'retry' => 0
];
$rcx = new RollingCurlX;
$rcx->addRequest($url, null, $complete, $user_data);
$rcx->execute();
//will retry up to 5 times until it gets a response before getting here
```

**Comment by nikola8** [comment]
Thank you.
I have try this code but it goes into unlimited iterations because $retry is set to 0 on each entrance to function.

**Comment by marcushat** [comment]
Did you forget the reference "=&" not "="?

**Comment by nikola8** [comment]
You mean this part:
          ${$var_name} =& $val;

I have used it exactly like you wrote it here as I copy/paste it.

**Comment by marcushat** [comment]
Ohhh, sorry, it should be `${$var_name} =& $user_data[$var_name];` because it's a reference. It works though; just tried it.
