### ISSUE TITLE
How many concurrent connections are you using?

### ISSUE THREAD

**Issue by logless** [marcushat/RollingCurlX#17]
I noticed that performance is best when only about 5 connections are used (almost 100% success rate). If 20 are used, many requests fail/timeout etc. and often the total execution time is longer than with only 5 concurrent requests.

Is this a curl limitation or more related to server bandwidth? I'd love to know what experience other users have with number of concurrent connections.

**Comment by marcushat** [comment]
Almost definitely a server issue. I did a lot of tests on this when I was making it and found dramatic differences depending on the resources/limits of the server you're sending the requests to and your bandwidth.
