### ISSUE TITLE
times setup

### ISSUE THREAD

**Issue by lehmannwebdev** [marcushat/RollingCurlX#19]
There is bug with setTimeout.

function setTimeout($timeout) set time in seconds:
$this->_timeout = $timeout**/1000** 

but when you set curl options in buildOptions(array $request) you should set time in seconds but you once again make **/1000**

$options[CURLOPT_CONNECTTIMEOUT] = max(1, $this->_timeout/1000); //minimum of 1 second
$options[CURLOPT_TIMEOUT] = $this->_timeout/1000;

**Comment by Kianda** [comment]
God! Thanks!

**Comment by whataboutpereira** [comment]
I as well stumbled upon the issue. setTimeout is indeed buggy in that it divides the microseconds when it shouldn't, because it's done later.

**Comment by marcushat** [comment]
Will fix.

**Comment by marcushat** [comment]
Resolved in newest version. Switched to using `CURLOPT_CONNECTTIMEOUT_MS` and `CURLOPT_TIMEOUT_MS`. `CURLOPT_CONNECTTIMEOUT` and `CURLOPT_TIMEOUT` will be unset to avoid conflict
