### ISSUE TITLE
fn: addRequest  might missing variable declaration

### ISSUE THREAD

**Issue by myworkpool** [marcushat/RollingCurlX#2]
When I run the script, it has error about variable in the function :  addRequest

in line 45,  should we declare $user_data as array,  as same as $post_data?

OLD:  
,,,,,,
public function addRequest(
                        $url,
                        array $post_data = NULL,
                        callable $callback = NULL, //individual callback
                        $user_data = NULL,
                        array $options = NULL, //individual cURL options
                        array $headers = NULL //individual cURL request headers
,,,,,

TO BE:

,,,,,,,
public function addRequest(
                        $url,
                        array $post_data = NULL,
                        callable $callback = NULL, //individual callback
                        array $user_data = NULL,  // <<<<< Add array declaration
                        array $options = NULL, //individual cURL options
                        array $headers = NULL //individual cURL request headers
,,,,,,

Im not a PHP fan, just a proj. manager,  so Im not sure should it need to declare

@marcushat   thanks for your previous fast response

**Comment by marcushat** [comment]
No, this is by design, I didn't type hint $user_data purposefully. $user_data, unlike $post_data, should be able to be an object, a string, an array, whatever you want really.

It shouldn't be throwing an error though, can you please comment the full error message that you're getting?

**Comment by myworkpool** [comment]
It seems that I got problem because of apply my array.

The issue may now close :)
