### ISSUE TITLE
Unable to get this to work

### ISSUE THREAD

**Issue by mattnuns** [marcushat/RollingCurlX#20]
Hi Marcus,

I cant seem to get this to work at all, I'm must be doing something extremely wrong as I don't seem to be able to get any output from simple requests. Do you happen to have a snippet of code that actually runs a request and outputs the returned data, if so I'd greatly appreciate it so I can learn how this works?

Thanks,

Matt

**Comment by marcushat** [comment]
Post your code and I'll take a look

**Comment by paamayim** [comment]
I had the same issue. It turns out that there was an erronous check for CURLOPT_HEADER

Line 204 needs to be changed to:
`if($response && (!empty($this->_options[CURLOPT_HEADER]) || !empty($options[CURLOPT_HEADER]))) {`

**Comment by bastienvans** [comment]
@iautomation This fixes the empty $response in the callback. Thank you!

**Comment by marcushat** [comment]
Resolved.
`$this->_options` can change between when the request was started and when the response is processed so the above won't do. Use the fix in the latest version instead.
