### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by vitalygoji** [marcushat/RollingCurlX#21]
I apologize in advance If my question is kinda stupid, but I can't figure this on out..
Before I started using RollingCurlX I tested it in a loop with THOUSANDS calls (to the same URL) and it worked! Now I put it in real life situation (calling different URLs) and I see that my program executes only 10 calls and for the rest of them just waiting to timeout.
This is what happens:
I queue 12 calls
after timeout I see that 10 were processed but 2 were just sitting waiting for timeout. 
Maybe somebody experienced something like this?  
Thank you guys!

**Comment by marcushat** [comment]
What do you mean by "just sitting waiting for a timeout"? Were these requests sent and did their callbacks get called? If they weren't sent did your script timeout?

This most likely has to do with the default maxConcurrency of 10 if you omit it in the constructor.

**Comment by marcushat** [comment]
Closing since no response. If that wasn't the issue then let us know.
