### ISSUE TITLE
CURLOPT_POST not respected in some circumstances

### ISSUE THREAD

**Issue by marcushat** [marcushat/RollingCurlX#24]
Appears to be undocumented issue with curl. Will use CURLOPT_CUSTOMREQUEST instead

**Comment by tsirolnik** [comment]
Please add an example... Reproduction of the bug... Something

**Comment by marcushat** [comment]
Wasn't able to reproduce it. I believe it was because it checks if `$post_data` is falsey instead of NULL like it should. Changed in newest version.
