### ISSUE TITLE
New constants broke compatibility with Curl < 7.16.2.

### ISSUE THREAD

**Issue by whataboutpereira** [marcushat/RollingCurlX#27]
These changes broke compatibility for me (stuck with Curl 7.15.5 here).

+        $options[CURLOPT_CONNECTTIMEOUT_MS] = $this->_timeout; //minimum of 1 second
+        $options[CURLOPT_TIMEOUT_MS] = $this->_timeout;

According to the PHP manual, *_MS constants are available since 7.16.2.

**Comment by marcushat** [comment]
It says curl version 7.16.2, which was released 10 years ago. How is this breaking compatibility for you, are you getting errors? This is v2.0 so there may be breaking changes.

**Comment by whataboutpereira** [comment]
Pretty old indeed! Execution just stopped with "no options set". For now I reverted to the old constants.

You may want to point out the requirements for Curl 7.16.2 in v2.0.

Thanks!

**Comment by marcushat** [comment]
Looks like those older versions are still pretty popular so I'm going to add support. It'll check the version and only use *_MS options if newer than v7.16.2

**Comment by marcushat** [comment]
Fixed in newest version v3. Please upgrade

**Comment by whataboutpereira** [comment]
Unfortunately it is still erroring.

It errors when it's trying to unset the (undefined) CURLOPT_CONNECTTIMEOUT_MS in the < 7.16.2 branch.

I changed my version to omit unsetting CURLOPT_CONNECTTIMEOUT_MS and CURLOPT_TIMEOUT_MS there.

I also considered changing the whole thing to use defined("CURLOPT_CONNECTTIMEOUT_MS") instead of the version check, but left it as it is atm.
