### ISSUE TITLE
Recoverable error: Argument 3 passed to RollingCurlX::addRequest() must be callable, string given, called in

### ISSUE THREAD

**Issue by mattguy88** [marcushat/RollingCurlX#28]
I get this error anytime that I check the $_GET request first.
`Recoverable error: Argument 3 passed to RollingCurlX::addRequest() must be callable, string given, called in`...

It's extremely odd and I haven't been able to figure it out. I do not get the error when I take off the Get check.  I get the error even with isset.

```php
if(!empty($_GET['isbn'])){
    $RCX = new RollingCurlX(10);   
    $options = [CURLOPT_FOLLOWLOCATION => true];
    $RCX->addRequest("http://www.google.com", $post_data, 'func', $user_data, $options, $headers);

    function func($response, $url, $request_info, $user_data, $time) {
        echo $response;  
    }             
    $RCX->execute();
}
```

**Comment by marcushat** [comment]
I can't help you unless you post your full code and the error you're getting. What is `$post_data`, `$user_data`, `$headers`?  I'm thinking this isn't a problem with the class though.

**Comment by marcushat** [comment]
You need to declare your callback function before you try to pass it to addRequest() or else it's just a regular string instead of callable. Php doesn't hoist functions to the top of the file so you have declare them before you use them(passing as argument with a callable type is using it, even though it hasn't tried to invoke it yet)

**Comment by marcushat** [comment]
So this should work

```php
if(!empty($_GET['isbn'])){
    $RCX = new RollingCurlX(10);
    $options = [CURLOPT_FOLLOWLOCATION => true];
    function func($response, $url, $request_info, $user_data, $time) {
        echo $response;
    }
    $RCX->addRequest("http://www.google.com", $post_data, 'func', $user_data, $options, $headers);

    $RCX->execute();
}
```

**Comment by mattguy88** [comment]
Ahhh OK! Thanks! This is my first time using anything with a callback and
since I wasn't wasn't familiar with it, I was just using the readme which
really didn't say that it needed to be in any kind of order. It's just so
weird that it was working properly until it was put into a ifelse check.

Thanks again!!

**Comment by marcushat** [comment]
Shouldn't have been working without the if/else either unless you declared the function beforehand.

**Comment by marcushat** [comment]
And updated the readme

**Comment by mattguy88** [comment]
Nope it works 100% if I leave out the if(isset) which is why I spent an
hour trying to figure out why 😂

What's your PayPal address? I'm going to send you some beer money

**Comment by marcushat** [comment]
Paypal is: (redacted)

Also if you could could post or email the code without the isset that'd be great too, because my understanding is that it shouldn't work and I'd like to know why it does.

**Comment by mattguy88** [comment]
<?php
require_once '../classes/rollingcurlx.class.php';

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$RCX = new RollingCurlX(10);

$options=$post_data=$user_data=$headers = null;

$RCX->addRequest("http://www.google.com", $post_data, 'func', $user_data, $options, $headers);

function func($response, $url, $request_info, $user_data, $time) {
    echo $response;
}

$RCX->execute();
?>

**Comment by marcushat** [comment]
Thanks for the money dude!

So it seems the php parser is smart enouph to know that 'func' will be available as a function if it's declared on the global scope(as in not inside any conditionals), whereas it has to wait until runtime to figure this out it it's declared inside the if. At runtime it's not available at the line that it's passed so it throws the error. Learned something new.

**Comment by marcushat** [comment]
Oh, and it's really bad practice to declare functions conditionally. If you're you going to do it that way then use anonymous functions like so: 

```php
if(!empty($_GET['isbn'])){
    $RCX = new RollingCurlX(10);
    $options = [CURLOPT_FOLLOWLOCATION => true];

    $func = function($response, $url, $request_info, $user_data, $time) {
        echo $response;
    }
    $RCX->addRequest("http://www.google.com", $post_data, $func, $user_data, $options, $headers);

    $RCX->execute();
}
```

...or declare them globally and use them conditionally
