### ISSUE TITLE
Return Response in any way, instead of false in case of Error

### ISSUE THREAD

**Issue by tylkomat** [marcushat/RollingCurlX#30]
Let the user decide what to do in case of error, don't silently ignore it.

Therefore [these lines](https://github.com/marcushat/RollingCurlX/blob/master/src/rollingcurlx.class.php#L215-L219) should be replaced with just the else part.

**Comment by marcushat** [comment]
If you need that to check that you can use ```$request_info['http_code'] ``` and get the response yourself from ```curl_multi_getcontent($reponse_info['ch'])```. Not changing ```$response``` because I think for the majority of cases, just need to know if it was 200 or not.
