### ISSUE TITLE
Getting a response back from the callback function

### ISSUE THREAD

**Issue by alexscott64** [marcushat/RollingCurlX#31]
Hey, I'm pretty new to this so forgive me if this is not actually an issue.

I'm just trying to do something simple:

make a request, get a response, and print it out:

```
-------------------
test_request.php
------------------
$rcx = new RollingCurlX(10);
$url = '/path/to/script/test.php';
$post_data = array('hello' => 'world');
$user_data = array('test' => 'this');
$options = array(CURLOPT_FOLLOWLOCATION => false);
function callback_function($response, $url, $request_info, $user_data, $time){
    echo '<pre>response:<br>';
    print_r($response);
    echo '</pre>';
}
$rcx->addRequest($url,$post_data,'callback_function',$user_data,$options);
$rcx->execute();
exit;
```

```
-------------------
/path/to/script/test.php
------------------
echo 'hello world';
$json_test = array('check' => 'this');
echo json_encode($json_test,true);
print_r($json_test);
exit;
```

No matter what I do, `$response` is always `false`.. is there some way I should be getting the data back as a response? Or do I just have to trust that RollingCurlX is working correctly? Sorry again if this is an obvious question, I don't really understand this super well.

**Comment by marcushat** [comment]
Curl is for http requests. $url must be a url like one you type in your browser. You can't make an http request to a file like you are trying to do.

**Comment by alexscott64** [comment]
Thanks for the quick response, I appreciate it. That was my bad then! I went down a rabbit hole of trying to find a way to essentially run a function asynchronously using PHP, and didn't  realize $url had to actually be a url, lol.
