### ISSUE TITLE
$request_maps should be $request_map

### ISSUE THREAD

**Issue by katjuncker** [marcushat/RollingCurlX#35]
https://github.com/marcushat/RollingCurlX/blob/ffdcd255f3ee726791f3af0df4a23462ae0835f8/src/rollingcurlx.class.php#L247

Typo in variable name $request_maps: looks like it should be $request_map.

**Comment by marcushat** [comment]
Thanks, that function's not currently being used though.

**Comment by katjuncker** [comment]
Yeah, I noticed that after I created the issue. My IDE complained about it and I figured there shouldn't be logic errors in the repo.

**Comment by marcushat** [comment]
I agree, will fix

**Comment by katjuncker** [comment]
Cool beans! I didn't mean to be nit-picky. Your repo really helped me out during some performance benchmarking today. Keep up the good work!

**Comment by marcushat** [comment]
Cool, love to hear that! And fixed
