### ISSUE TITLE
Timeout is wrong

### ISSUE THREAD

**Issue by plankes-projects** [marcushat/RollingCurlX#36]
At setting the timeout you devide by 1000 to get it to seconds.

```    
public function setTimeout($timeout) { //in milliseconds
	if($timeout > 0) {
		$this->_timeout = $timeout/1000; //to seconds
	}
}
```

Afterwards, when using it, you divide again which results in wrong values.

```
$options[CURLOPT_CONNECTTIMEOUT] = max(1, $this->_timeout/1000); //minimum of 1 second
$options[CURLOPT_TIMEOUT] = $this->_timeout/1000;
```

Either remove the division in the setter or at curl creation.

Greets, klaus

**Comment by marcushat** [comment]
Thanks. Will fix

**Comment by whataboutpereira** [comment]
To save you the trouble, it was fixed some while ago already. :)

**Comment by marcushat** [comment]
Thought so, will double check this morn

**Comment by plankes-projects** [comment]
Right, seems so. But it did not make it to composer though. Required it one day before I opened the issue.

**Comment by marcushat** [comment]
I'm not the one behind the composer version
