### ISSUE TITLE
Timeout is divided by 1000 twice

### ISSUE THREAD

**Issue by Worper1997** [marcushat/RollingCurlX#40]
You know you're doing this twice right?
Line 46
$this->_timeout = $timeout/1000; //to seconds
Line 150,151
$options[CURLOPT_CONNECTTIMEOUT] = max(3, $this->_timeout/1000); //minimum of 1 second
$options[CURLOPT_TIMEOUT] = $this->_timeout/1000;
I really don't know why you're taking miliseconds and converting them to seconds. Seems unnecessary
I'm uploading my file including the fix for https://github.com/marcushat/RollingCurlX/issues/39

[rollingcurlx.class.php.zip](https://github.com/marcushat/RollingCurlX/files/2148494/rollingcurlx.class.php.zip)

**Comment by whataboutpereira** [comment]
You're looking at some old version, this was fixed some while ago.
