### ISSUE TITLE
Regarding this project

### ISSUE THREAD

**Issue by SaratSatyanarayana** [marcushat/RollingCurlX#43]
hii,im new to php.i want to make a project which downloads the images or videos from an instagram link.i reffered to your project..can you help me how to make it..as iam a beginnner im unable to understand..can you tell me step by step procedure so that i can learn easily and understand easily.

saratharjunakh@gmail.com

**Comment by marcushat** [comment]
Doesn’t get much easier than the instructions on the readme. I’m not a teacher but good luck learning
