### ISSUE TITLE
Post Data must be array?

### ISSUE THREAD

**Issue by mowasfi7** [marcushat/RollingCurlX#5]
Hi,

In `addRequest()` you're expecting the post data to be an array. In my case I just need to pass a string so I had to remove the type array.

Moreover, you already check if it's an array or not on:

``` php
$options[CURLOPT_POSTFIELDS] = is_array($post_data)? http_build_query($post_data) : $post_data;
```

so why force it to be an array if you're going to check if it's an array or not anyways?

I had to modify:

``` php
public function addRequest(
                        $url,
                        array $post_data = NULL,
```

to:

``` php
public function addRequest(
                        $url,
                        $post_data = NULL,
```

But thanks anyways you rock!

**Comment by marcushat** [comment]
Can you POST just a string? I've only used post with forms, so my understanding was that post data has to be a key/value pair just like the query string in a GET request. Is that incorrect? If it is, please provide a link to the spec and I'll surely change it.

Nice to see people are using this.

**Comment by mowasfi7** [comment]
I'm using it with a JSON API, so the web service expects a request in the form of a JSON string rather than a traditional key/value pair :)

So removing the type array allows me to post arrays when I want and string when I want, knowing that you'll check if it's an array and use the http_build_query if it is

**Comment by marcushat** [comment]
Okay, I see, seems you can post just about anything. I'll remove the type hint.
