### ISSUE TITLE
creating array throws error:

### ISSUE THREAD

**Issue by rene-hermenau** [marcushat/RollingCurlX#7]
This throws an error on a clients website:

private $_options = [];

error: syntax error, unexpected '[' 

Isnt this syntax supported by all php versions?

**Comment by marcushat** [comment]
That's php's short array syntax; you can use it as of 5.4.

http://php.net/manual/en/language.types.array.php

And glad to see people are using this.

**Comment by rene-hermenau** [comment]
Thanks Marcus, i had to change it to private $_options = array(); to be compatible with php < 5.4
I love this class, you can see it running here:  https://github.com/mashshare/Mashshare/blob/developer/includes/mashengine.php

**Comment by marcushat** [comment]
Cool cool.
Just a note though, Php 5.3 has reached it's End of Life, so it was purposefully not supported to encourage the use of the much improved newer versions.

**Comment by rene-hermenau** [comment]
Sure, i know this but i use it for WordPress plugins and i have to make sure that it runs on as much versions as possible. Unfortunately 5.3 is still used by a lot of different providers.
