### ISSUE TITLE
Number of max concurrent calls on the class gets overwritten along the life of the object

### ISSUE THREAD

**Issue by j3j5** [marcushat/RollingCurlX#9]
When using the class, I expect the number of max concurrent calls I use on the constructor to be kept along the life of the object (unless a call to setMaxConcurrent() is done) but if you add less request than this number, execute, and then try to add new requests the number of max concurrent calls for the object gets overwritten by the amount of calls made on the first execute().

**Comment by marcushat** [comment]
dumb mistake. fixed

**Comment by nmcgann** [comment]
This isn't actually fixed in the current release. Changing the first bit of `execute()` to th following solves it:
````
    //Execute the request queue
    public function execute() {
        //limit initial parallel requests to _maxConcurrent and don't overwrite _maxConcurrent.
        $init_request_count = (count($this->requests) > $this->_maxConcurrent) 
                                ? $this->_maxConcurrent 
                                : count($this->requests);
        //the request map that maps the request queue to request curl handles
        $requests_map = [];
        $multi_handle = curl_multi_init();

        //start processing the initial request queue
        for($i = 0; $i < $init_request_count; $i++) {
            $this->init_request($i, $multi_handle, $requests_map);
        }

````

**Comment by marcushat** [comment]
Resolved in newest version v3. Please upgrade
